<?xml version="1.0" encoding="UTF-8" ?>
<Package name="Airport" format_version="4">
    <Manifest src="manifest.xml" />
    <BehaviorDescriptions>
        <BehaviorDescription name="behavior" src="main" xar="behavior.xar" />
    </BehaviorDescriptions>
    <Dialogs />
    <Resources>
        <File name="README" src="README.md" />
        <File name="chardetect" src="lib/bin/chardetect.exe" />
        <File name="DESCRIPTION" src="lib/certifi-2018.4.16.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="lib/certifi-2018.4.16.dist-info/INSTALLER" />
        <File name="LICENSE" src="lib/certifi-2018.4.16.dist-info/LICENSE.txt" />
        <File name="METADATA" src="lib/certifi-2018.4.16.dist-info/METADATA" />
        <File name="RECORD" src="lib/certifi-2018.4.16.dist-info/RECORD" />
        <File name="WHEEL" src="lib/certifi-2018.4.16.dist-info/WHEEL" />
        <File name="metadata" src="lib/certifi-2018.4.16.dist-info/metadata.json" />
        <File name="top_level" src="lib/certifi-2018.4.16.dist-info/top_level.txt" />
        <File name="__init__" src="lib/certifi/__init__.py" />
        <File name="__main__" src="lib/certifi/__main__.py" />
        <File name="cacert" src="lib/certifi/cacert.pem" />
        <File name="core" src="lib/certifi/core.py" />
        <File name="DESCRIPTION" src="lib/chardet-3.0.4.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="lib/chardet-3.0.4.dist-info/INSTALLER" />
        <File name="METADATA" src="lib/chardet-3.0.4.dist-info/METADATA" />
        <File name="RECORD" src="lib/chardet-3.0.4.dist-info/RECORD" />
        <File name="WHEEL" src="lib/chardet-3.0.4.dist-info/WHEEL" />
        <File name="entry_points" src="lib/chardet-3.0.4.dist-info/entry_points.txt" />
        <File name="metadata" src="lib/chardet-3.0.4.dist-info/metadata.json" />
        <File name="top_level" src="lib/chardet-3.0.4.dist-info/top_level.txt" />
        <File name="__init__" src="lib/chardet/__init__.py" />
        <File name="big5freq" src="lib/chardet/big5freq.py" />
        <File name="big5prober" src="lib/chardet/big5prober.py" />
        <File name="chardistribution" src="lib/chardet/chardistribution.py" />
        <File name="charsetgroupprober" src="lib/chardet/charsetgroupprober.py" />
        <File name="charsetprober" src="lib/chardet/charsetprober.py" />
        <File name="__init__" src="lib/chardet/cli/__init__.py" />
        <File name="chardetect" src="lib/chardet/cli/chardetect.py" />
        <File name="codingstatemachine" src="lib/chardet/codingstatemachine.py" />
        <File name="compat" src="lib/chardet/compat.py" />
        <File name="cp949prober" src="lib/chardet/cp949prober.py" />
        <File name="enums" src="lib/chardet/enums.py" />
        <File name="escprober" src="lib/chardet/escprober.py" />
        <File name="escsm" src="lib/chardet/escsm.py" />
        <File name="eucjpprober" src="lib/chardet/eucjpprober.py" />
        <File name="euckrfreq" src="lib/chardet/euckrfreq.py" />
        <File name="euckrprober" src="lib/chardet/euckrprober.py" />
        <File name="euctwfreq" src="lib/chardet/euctwfreq.py" />
        <File name="euctwprober" src="lib/chardet/euctwprober.py" />
        <File name="gb2312freq" src="lib/chardet/gb2312freq.py" />
        <File name="gb2312prober" src="lib/chardet/gb2312prober.py" />
        <File name="hebrewprober" src="lib/chardet/hebrewprober.py" />
        <File name="jisfreq" src="lib/chardet/jisfreq.py" />
        <File name="jpcntx" src="lib/chardet/jpcntx.py" />
        <File name="langbulgarianmodel" src="lib/chardet/langbulgarianmodel.py" />
        <File name="langcyrillicmodel" src="lib/chardet/langcyrillicmodel.py" />
        <File name="langgreekmodel" src="lib/chardet/langgreekmodel.py" />
        <File name="langhebrewmodel" src="lib/chardet/langhebrewmodel.py" />
        <File name="langhungarianmodel" src="lib/chardet/langhungarianmodel.py" />
        <File name="langthaimodel" src="lib/chardet/langthaimodel.py" />
        <File name="langturkishmodel" src="lib/chardet/langturkishmodel.py" />
        <File name="latin1prober" src="lib/chardet/latin1prober.py" />
        <File name="mbcharsetprober" src="lib/chardet/mbcharsetprober.py" />
        <File name="mbcsgroupprober" src="lib/chardet/mbcsgroupprober.py" />
        <File name="mbcssm" src="lib/chardet/mbcssm.py" />
        <File name="sbcharsetprober" src="lib/chardet/sbcharsetprober.py" />
        <File name="sbcsgroupprober" src="lib/chardet/sbcsgroupprober.py" />
        <File name="sjisprober" src="lib/chardet/sjisprober.py" />
        <File name="universaldetector" src="lib/chardet/universaldetector.py" />
        <File name="utf8prober" src="lib/chardet/utf8prober.py" />
        <File name="version" src="lib/chardet/version.py" />
        <File name="DESCRIPTION" src="lib/idna-2.6.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="lib/idna-2.6.dist-info/INSTALLER" />
        <File name="METADATA" src="lib/idna-2.6.dist-info/METADATA" />
        <File name="RECORD" src="lib/idna-2.6.dist-info/RECORD" />
        <File name="WHEEL" src="lib/idna-2.6.dist-info/WHEEL" />
        <File name="metadata" src="lib/idna-2.6.dist-info/metadata.json" />
        <File name="top_level" src="lib/idna-2.6.dist-info/top_level.txt" />
        <File name="__init__" src="lib/idna/__init__.py" />
        <File name="codec" src="lib/idna/codec.py" />
        <File name="compat" src="lib/idna/compat.py" />
        <File name="core" src="lib/idna/core.py" />
        <File name="idnadata" src="lib/idna/idnadata.py" />
        <File name="intranges" src="lib/idna/intranges.py" />
        <File name="package_data" src="lib/idna/package_data.py" />
        <File name="uts46data" src="lib/idna/uts46data.py" />
        <File name="DESCRIPTION" src="lib/requests-2.18.4.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="lib/requests-2.18.4.dist-info/INSTALLER" />
        <File name="METADATA" src="lib/requests-2.18.4.dist-info/METADATA" />
        <File name="RECORD" src="lib/requests-2.18.4.dist-info/RECORD" />
        <File name="WHEEL" src="lib/requests-2.18.4.dist-info/WHEEL" />
        <File name="metadata" src="lib/requests-2.18.4.dist-info/metadata.json" />
        <File name="top_level" src="lib/requests-2.18.4.dist-info/top_level.txt" />
        <File name="__init__" src="lib/requests/__init__.py" />
        <File name="__version__" src="lib/requests/__version__.py" />
        <File name="_internal_utils" src="lib/requests/_internal_utils.py" />
        <File name="adapters" src="lib/requests/adapters.py" />
        <File name="api" src="lib/requests/api.py" />
        <File name="auth" src="lib/requests/auth.py" />
        <File name="certs" src="lib/requests/certs.py" />
        <File name="compat" src="lib/requests/compat.py" />
        <File name="cookies" src="lib/requests/cookies.py" />
        <File name="exceptions" src="lib/requests/exceptions.py" />
        <File name="help" src="lib/requests/help.py" />
        <File name="hooks" src="lib/requests/hooks.py" />
        <File name="models" src="lib/requests/models.py" />
        <File name="packages" src="lib/requests/packages.py" />
        <File name="sessions" src="lib/requests/sessions.py" />
        <File name="status_codes" src="lib/requests/status_codes.py" />
        <File name="structures" src="lib/requests/structures.py" />
        <File name="utils" src="lib/requests/utils.py" />
        <File name="DESCRIPTION" src="lib/tinydb-3.9.0.post1.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="lib/tinydb-3.9.0.post1.dist-info/INSTALLER" />
        <File name="METADATA" src="lib/tinydb-3.9.0.post1.dist-info/METADATA" />
        <File name="RECORD" src="lib/tinydb-3.9.0.post1.dist-info/RECORD" />
        <File name="WHEEL" src="lib/tinydb-3.9.0.post1.dist-info/WHEEL" />
        <File name="metadata" src="lib/tinydb-3.9.0.post1.dist-info/metadata.json" />
        <File name="top_level" src="lib/tinydb-3.9.0.post1.dist-info/top_level.txt" />
        <File name="zip-safe" src="lib/tinydb-3.9.0.post1.dist-info/zip-safe" />
        <File name="__init__" src="lib/tinydb/__init__.py" />
        <File name="database" src="lib/tinydb/database.py" />
        <File name="middlewares" src="lib/tinydb/middlewares.py" />
        <File name="operations" src="lib/tinydb/operations.py" />
        <File name="queries" src="lib/tinydb/queries.py" />
        <File name="storages" src="lib/tinydb/storages.py" />
        <File name="utils" src="lib/tinydb/utils.py" />
        <File name="version" src="lib/tinydb/version.py" />
        <File name="DESCRIPTION" src="lib/urllib3-1.22.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="lib/urllib3-1.22.dist-info/INSTALLER" />
        <File name="METADATA" src="lib/urllib3-1.22.dist-info/METADATA" />
        <File name="RECORD" src="lib/urllib3-1.22.dist-info/RECORD" />
        <File name="WHEEL" src="lib/urllib3-1.22.dist-info/WHEEL" />
        <File name="metadata" src="lib/urllib3-1.22.dist-info/metadata.json" />
        <File name="top_level" src="lib/urllib3-1.22.dist-info/top_level.txt" />
        <File name="__init__" src="lib/urllib3/__init__.py" />
        <File name="_collections" src="lib/urllib3/_collections.py" />
        <File name="connection" src="lib/urllib3/connection.py" />
        <File name="connectionpool" src="lib/urllib3/connectionpool.py" />
        <File name="__init__" src="lib/urllib3/contrib/__init__.py" />
        <File name="__init__" src="lib/urllib3/contrib/_securetransport/__init__.py" />
        <File name="bindings" src="lib/urllib3/contrib/_securetransport/bindings.py" />
        <File name="low_level" src="lib/urllib3/contrib/_securetransport/low_level.py" />
        <File name="appengine" src="lib/urllib3/contrib/appengine.py" />
        <File name="ntlmpool" src="lib/urllib3/contrib/ntlmpool.py" />
        <File name="pyopenssl" src="lib/urllib3/contrib/pyopenssl.py" />
        <File name="securetransport" src="lib/urllib3/contrib/securetransport.py" />
        <File name="socks" src="lib/urllib3/contrib/socks.py" />
        <File name="exceptions" src="lib/urllib3/exceptions.py" />
        <File name="fields" src="lib/urllib3/fields.py" />
        <File name="filepost" src="lib/urllib3/filepost.py" />
        <File name="__init__" src="lib/urllib3/packages/__init__.py" />
        <File name="__init__" src="lib/urllib3/packages/backports/__init__.py" />
        <File name="makefile" src="lib/urllib3/packages/backports/makefile.py" />
        <File name="ordered_dict" src="lib/urllib3/packages/ordered_dict.py" />
        <File name="six" src="lib/urllib3/packages/six.py" />
        <File name="__init__" src="lib/urllib3/packages/ssl_match_hostname/__init__.py" />
        <File name="_implementation" src="lib/urllib3/packages/ssl_match_hostname/_implementation.py" />
        <File name="poolmanager" src="lib/urllib3/poolmanager.py" />
        <File name="request" src="lib/urllib3/request.py" />
        <File name="response" src="lib/urllib3/response.py" />
        <File name="__init__" src="lib/urllib3/util/__init__.py" />
        <File name="connection" src="lib/urllib3/util/connection.py" />
        <File name="request" src="lib/urllib3/util/request.py" />
        <File name="response" src="lib/urllib3/util/response.py" />
        <File name="retry" src="lib/urllib3/util/retry.py" />
        <File name="selectors" src="lib/urllib3/util/selectors.py" />
        <File name="ssl_" src="lib/urllib3/util/ssl_.py" />
        <File name="timeout" src="lib/urllib3/util/timeout.py" />
        <File name="url" src="lib/urllib3/util/url.py" />
        <File name="wait" src="lib/urllib3/util/wait.py" />
    </Resources>
    <Topics />
    <IgnoredPaths />
</Package>
